**/Assets/AddressableAssetsData/*/*.bin*
**/assets/addressableassetsdata/*/*.bin*
**/Assets/AssetStoreTools
**/assets/assetstoretools
**/assets/streamingassets/*/aa/*
**/Assets/StreamingAssets/aa.meta
*.apk
*.booproj
*.csproj
*.mdb
*.mdb.meta
*.opendb
*.pdb
*.pdb.meta
*.pidb
*.pidb.meta
*.private
*.private.meta
*.sln
*.suo
*.svd
*.tmp
*.unitypackage
*.unityproj
*.user
*.userprefs
*.VC.db
.collabignore
.consulo
.DS_Store*
.gradle
.vs
/Assets/Plugins/PlasticSCM*
/assets/plugins/PlasticSCM*
/ignore.conf
^*.private.[0-9]+$
^*.private.[0-9]+.meta$
Build
build
Builds
builds
crashlytics-build.properties
Desktop.ini
ExportedObj
Library
library
Logs
logs
MemoryCaptures
memorycaptures
Obj
obj
sysinfo.txt
Temp
temp
Thumbs.db
UserSettings
usersettings
